version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./images:/app/images:rw # Добавлено rw для доступа к изображениям
    restart: unless-stopped

#  app:
#    build: .
#    container_name: app
#    depends_on:
#      - nginx
#    volumes:
#      - ./images:/app/images:rw # Добавлено rw для доступа к изображениям
#      - ./files.db:/app/files.db # Монтируем БД
#      - ./:/app
#    restart: unless-stopped