services:

  app:
    build: .
    image: pichost
    container_name: app
    environment:
      - DOMAIN=pichosting.mooo.com
    volumes:
      - ./files.db:/app/files.db
      - ./static:/app/static
      - ./images:/app/images
      - ./thumbnails:/app/thumbnails
      - ./templates:/app/templates
      - ./gunicorn_config.py:/app/gunicorn_config.py
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./images:/app/images:rw
      - ./thumbnails:/app/thumbnails:rw
    restart: always
    depends_on:
      - app
