---
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - MAX_UPLOAD_SIZE=5000M
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: >
      sh -c "
        envsubst '$$MAX_UPLOAD_SIZE' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "

