services:
  app:
    build: .
    image: pichost
    container_name: app
    environment:
      - DOMAIN=pichosting.mooo.com
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/pichosting
      - POSTGRES_DB=pichosting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      # OAuth Configuration
      - OAUTH_CLIENT_ID=pichost
      - OAUTH_CLIENT_SECRET=zmuJN1TbiqXImGipguw7BhB14gFsgFFv
      - OAUTH_METADATA_URL=https://ja.gradient.ru/keycloak/realms/pichost/.well-known/openid-configuration
      - OAUTH_SCOPE=openid profile email
      - OAUTH_CODE_CHALLENGE_METHOD=S256
      # Fallback OAuth URLs (если metadata недоступна)
      - OAUTH_BASE_URL=https://ja.gradient.ru/keycloak/realms/pichost/protocol/openid-connect
      - OAUTH_AUTHORIZE_URL=https://ja.gradient.ru/keycloak/realms/pichost/protocol/openid-connect/auth
      - OAUTH_ACCESS_TOKEN_URL=https://ja.gradient.ru/keycloak/realms/pichost/protocol/openid-connect/token
      - OAUTH_LOGOUT_URL=https://ja.gradient.ru/keycloak/realms/pichost/protocol/openid-connect/logout
      - SECRET_KEY=your-very-secure-secret-key-change-in-production
    volumes:
      - ./static:/app/static
      - ./images:/app/images
      - ./thumbnails:/app/thumbnails
      - ./templates:/app/templates
      - ./gunicorn_config.py:/app/gunicorn_config.py
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./images:/app/images:rw
      - ./thumbnails:/app/thumbnails:rw
    restart: always
    depends_on:
      - app

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=pichosting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/pichosting
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
