services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./images:/app/images:rw
      - ./thumbnails:/app/thumbnails:rw
    restart: always

  app:
    build: .
    image: pichost
    container_name: app
    depends_on:
      - nginx
    environment:
      - DOMAIN=pichosting.mooo.com
    volumes:
      - ./files.db:/app/files.db
      - ./:/app
    restart: always
